idf_component_register(
    SRCS
        "main.c"
        "observore_detect.c"
        "observore_track.c"
        "observore_mute.c"
        "observore_netcfg.c"
        "observore_auth.c"
        "observore_nvs.c"
        "observore_util.c"
        "observore_notify.c"
        "observore_notify_fmt.c"
        "observore_ble.c"
        "observore_wifi.c"
        "observore_web.c"
        "observore_led.c"
    INCLUDE_DIRS "."
    REQUIRES
        bt
        driver
        esp_event
        esp_http_server
        esp_netif
        esp_timer
        espressif__mdns
        esp-tls
        esp_http_client
        esp_wifi
        nvs_flash
    EMBED_FILES "www/index.html"
)
