#!/usr/bin/env python3
"""Render a monospace typeface into an 8x16 one-bit font for the display.

Generated, never hand-edited, like the OUI table. A bitmap font typed in by
hand is 1,520 bytes of opportunities to draw the wrong letter, and the first
place anyone would notice is on a screen across the room. Rendering a real
face and reading the pixels back cannot make that mistake.

    python3 tools/gen_font.py > main/observore_font.h
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FACE = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
W, H, SIZE = 8, 16, 14          # cell, and the point size that fits it
FIRST = 0x20                    # printable ASCII starts here
ASCII_LAST = 0x7E               # ...and ends here

# Icons, appended immediately after printable ASCII.
#
# They come from the proportional face, because the monospace one does not
# have them: DejaVuSansMono draws U+2B21 as the empty .notdef rectangle. That
# very nearly shipped -- PIL reports a mask size of (8, 12) for it, which
# looks like a glyph until you print the pixels and find a box. Hence
# box_of() below: a codepoint that renders the same as one known to be absent
# is not a glyph, and the generator stops rather than emitting a rectangle
# labelled "mesh".
#
# A symbol does not need the mono face's metrics, only the cell. 11pt at a
# one-pixel left and one-pixel down offset puts the hexagon's baseline on the
# same row as a capital X's.
ICON_FACE = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
ICON_SIZE, ICON_DX, ICON_DY = 11, -1, 1

# code -> (codepoint, name). Codes run on from ASCII_LAST, so adding one here
# is all it takes; #132 noted the mesh mark would not be the last icon wanted.
ICONS = [
    (0x2B21, "mesh"),           # WHITE HEXAGON, for a node that is warning
]
LAST = ASCII_LAST + len(ICONS)

def render(face, size, cp, dx, dy):
    img = Image.new("1", (W, H), 0)
    ImageDraw.Draw(img).text((dx, dy), chr(cp), font=ImageFont.truetype(face, size), fill=1)
    return [sum((img.getpixel((x, y)) & 1) << (7 - x) for x in range(W))
            for y in range(H)]


def box_of(face, size, dx, dy):
    """What this face draws for a codepoint it does not have.

    U+FFFF is a noncharacter and is in no font, so whatever comes back is the
    .notdef box. Comparing against it is how an icon that is silently missing
    becomes a failed build instead of a rectangle on the glass."""
    return render(face, size, 0xFFFF, dx, dy)


# Letters, from the monospace face. The baseline sits a little above the cell
# bottom so descenders fit.
rows = []
for code in range(FIRST, ASCII_LAST + 1):
    rows.append(render(FACE, SIZE, code, 0, -1))

icon_box = box_of(ICON_FACE, ICON_SIZE, ICON_DX, ICON_DY)
icon_art = []
for cp, name in ICONS:
    bits = render(ICON_FACE, ICON_SIZE, cp, ICON_DX, ICON_DY)
    if bits == icon_box or not any(bits):
        sys.exit("%s: U+%04X is not in %s -- it renders as the .notdef box"
                 % (name, cp, ICON_FACE.split("/")[-1]))
    rows.append(bits)
    icon_art.append((name, cp, bits))

print("/* Generated by tools/gen_font.py from %s at %dpt. Do not edit. */" % (FACE.split('/')[-1], SIZE))
print("#pragma once\n#include <stdint.h>\n")
print("#define OBSERVORE_FONT_W %d\n#define OBSERVORE_FONT_H %d" % (W, H))
print("#define OBSERVORE_FONT_FIRST 0x%02X\n#define OBSERVORE_FONT_LAST  0x%02X\n" % (FIRST, LAST))
print("/* Icons, after printable ASCII. Drawn below so the shape can be checked")
print(" * without a screen -- which is the only way anybody caught that the")
print(" * monospace face renders a hexagon as an empty rectangle.")
print(" *")
print(" * Each is one character, so it goes in a string. Keep it a separate")
print(" * literal from anything that follows: C hex escapes are greedy, so")
print(" * \"\\x7f3\" is one bad escape where OBSERVORE_GLYPH_MESH \"3\" is two")
print(" * literals the compiler joins. */")
for i, (name, cp, bits) in enumerate(icon_art):
    code = ASCII_LAST + 1 + i
    print("/* %s, U+%04X:" % (name, cp))
    for r in bits:
        print(" *   %s" % "".join("#" if (r >> (7 - x)) & 1 else "." for x in range(W)))
    print(" */")
    print("#define OBSERVORE_GLYPH_%s \"\\x%02x\"" % (name.upper(), code))
print("")
print("/* One byte per row, MSB is the leftmost pixel, %d rows per glyph. */" % H)
print("static const uint8_t OBSERVORE_FONT[%d][%d] = {" % (LAST - FIRST + 1, H))
for i, r in enumerate(rows):
    code = FIRST + i
    if code <= ASCII_LAST:
        c = chr(code)
        label = "'%s'" % (c if c not in "\\*/" else "chr")
    else:
        label = ICONS[code - ASCII_LAST - 1][1]
    print("    {%s}, /* %s */" % (", ".join("0x%02X" % b for b in r), label))
print("};")
