#!/usr/bin/env python3
"""Render a monospace typeface into an 8x16 one-bit font for the display.

Generated, never hand-edited, like the OUI table. A bitmap font typed in by
hand is 1,520 bytes of opportunities to draw the wrong letter, and the first
place anyone would notice is on a screen across the room. Rendering a real
face and reading the pixels back cannot make that mistake.

    python3 tools/gen_font.py > main/observore_font.h
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FACE = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
W, H, SIZE = 8, 16, 14          # cell, and the point size that fits it
FIRST, LAST = 0x20, 0x7E        # printable ASCII

font = ImageFont.truetype(FACE, SIZE)
rows = []
for code in range(FIRST, LAST + 1):
    img = Image.new("1", (W, H), 0)
    d = ImageDraw.Draw(img)
    # Baseline sits a little above the cell bottom so descenders fit.
    d.text((0, -1), chr(code), font=font, fill=1)
    rows.append([sum((img.getpixel((x, y)) & 1) << (7 - x) for x in range(W))
                 for y in range(H)])

print("/* Generated by tools/gen_font.py from %s at %dpt. Do not edit. */" % (FACE.split('/')[-1], SIZE))
print("#pragma once\n#include <stdint.h>\n")
print("#define OBSERVORE_FONT_W %d\n#define OBSERVORE_FONT_H %d" % (W, H))
print("#define OBSERVORE_FONT_FIRST 0x%02X\n#define OBSERVORE_FONT_LAST  0x%02X\n" % (FIRST, LAST))
print("/* One byte per row, MSB is the leftmost pixel, %d rows per glyph. */" % H)
print("static const uint8_t OBSERVORE_FONT[%d][%d] = {" % (LAST - FIRST + 1, H))
for i, r in enumerate(rows):
    c = chr(FIRST + i)
    label = c if c not in "\\*/" else "chr"
    print("    {%s}, /* '%s' */" % (", ".join("0x%02X" % b for b in r), label))
print("};")
