#!/usr/bin/env python3
"""Generate main/argus_oui_table.h from the IEEE MA-L registry.

OUI assignments are public facts published by the IEEE Registration Authority.
Regenerating from the source keeps the table current and auditable instead of
carrying a hand-maintained copy that silently rots.

    python3 tools/gen_oui_table.py            # download, generate
    python3 tools/gen_oui_table.py --csv oui.csv   # use a local copy
"""

import argparse
import csv
import io
import re
import sys
import urllib.request
from collections import OrderedDict

OUI_URL = "https://standards-oui.ieee.org/oui/oui.csv"

# Each entry: (category, [regexes matched case-insensitively against the
# IEEE "Organization Name" column]).  Order matters -- the first category that
# claims an OUI owns it, so specific categories precede general ones.
CATEGORIES = OrderedDict([
    ("BODYCAM", [
        r"\baxon enterprise\b",
        r"\btaser international\b",
    ]),
    ("ALPR", [
        r"\bflock safety\b",
        r"\bneology\b",
        r"\bjenoptik\b",
        r"\bredflex\b",
        r"\btattile\b",          # Italian ALPR / traffic-enforcement cameras
    ]),
    ("FLEET_TELEMATICS", [
        r"\bsamsara networks\b",
        r"\blytx\b",
        r"\bnetradyne\b",
    ]),
    ("DRONE", [
        r"\bdji technology\b",
        r"\bdji baiwang\b",
        r"\bskydio\b",
        r"\bparrot sa\b",
    ]),
    ("CAMERA", [
        r"\bhikvision\b",
        r"\bdahua technolog",
        r"\buniview technolog",
        r"\bamcrest\b",
        r"\breolink\b",
        r"\bswann communications\b",
        r"\blorex technology\b",
        r"\baxis communications\b",
        r"\bmobotix\b",
        r"\bvivotek\b",
        r"\bhanwha vision\b",
        r"\bhanwha nxmd\b",
        r"\bhanwha vision vietnam\b",
        r"\bbosch security systems\b",
        r"\bavigilon\b",
        r"\bverkada\b",
        r"\bgenetec\b",
        r"\bring llc\b",
        r"\bwyze labs\b",
        r"\barlo technology\b",
        r"\bnest labs\b",
        r"\bsimplisafe\b",
    ]),
])

# MAC prefixes that are not IEEE assignments but are worth flagging anyway.
# Kept separate and explicit so the generated file stays reproducible.
EXTRA = [
    # (oui, category, label)
]


def fetch(path):
    if path:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            return fh.read()
    sys.stderr.write("downloading %s ...\n" % OUI_URL)
    req = urllib.request.Request(OUI_URL, headers={"User-Agent": "argus-oui-gen"})
    with urllib.request.urlopen(req, timeout=180) as resp:
        return resp.read().decode("utf-8", errors="replace")


def normalise(org):
    """Collapse the registry's ragged vendor strings into a short label."""
    org = org.strip().strip('"').strip()
    org = re.sub(r"[,\.]?\s*(Co\.?|Corp\.?|Corporation|Inc\.?|Ltd\.?|Limited|"
                 r"LLC|GmbH|AB|SA|SRL|B\.?V\.?|Pty|S\.?A\.?S\.?|"
                 r"Technologies|Technology|Digital Technology)\b.*$", "", org,
                 flags=re.I)
    org = re.sub(r"\s+", " ", org).strip(" ,.-")
    return org[:23] or "unknown"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", help="local oui.csv instead of downloading")
    ap.add_argument("--out", default="main/argus_oui_table.h")
    args = ap.parse_args()

    compiled = OrderedDict(
        (cat, [re.compile(p, re.I) for p in pats])
        for cat, pats in CATEGORIES.items()
    )

    rows = []
    claimed = set()
    reader = csv.DictReader(io.StringIO(fetch(args.csv)))
    for row in reader:
        if row.get("Registry") != "MA-L":
            continue
        oui = (row.get("Assignment") or "").strip().upper()
        org = row.get("Organization Name") or ""
        if len(oui) != 6 or oui in claimed:
            continue
        for cat, pats in compiled.items():
            if any(p.search(org) for p in pats):
                rows.append((oui, cat, normalise(org)))
                claimed.add(oui)
                break

    for oui, cat, label in EXTRA:
        if oui not in claimed:
            rows.append((oui, cat, label))
            claimed.add(oui)

    rows.sort(key=lambda r: r[0])

    counts = OrderedDict((c, 0) for c in CATEGORIES)
    for _, cat, _ in rows:
        counts[cat] += 1

    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/gen_oui_table.py -- do not edit by hand.\n"
                 " *\n"
                 " * Source: IEEE MA-L registry, %s\n"
                 " * Vendor-to-category mapping lives in the generator.\n"
                 " */\n\n"
                 "#pragma once\n\n"
                 "#include \"argus_types.h\"\n\n" % OUI_URL)
        fh.write("/* %d prefixes: %s */\n" % (
            len(rows), ", ".join("%s=%d" % (c, n) for c, n in counts.items())))
        fh.write("static const argus_oui_t ARGUS_OUI_TABLE[] = {\n")
        for oui, cat, label in rows:
            fh.write("    {{0x%s, 0x%s, 0x%s}, ARGUS_CLASS_%s, \"%s\"},\n"
                     % (oui[0:2], oui[2:4], oui[4:6], cat, label))
        fh.write("};\n\n")
        fh.write("#define ARGUS_OUI_TABLE_LEN "
                 "(sizeof(ARGUS_OUI_TABLE) / sizeof(ARGUS_OUI_TABLE[0]))\n")

    sys.stderr.write("wrote %s: %d prefixes (%s)\n" % (
        args.out, len(rows),
        ", ".join("%s=%d" % (c, n) for c, n in counts.items())))


if __name__ == "__main__":
    main()
